import { OPENADE_PERMISSION_PROFILE_PAIRED_NOTIFICATION_PERMISSIONS, OPENADE_PERMISSION_PROFILE_PAIRED_PERMISSIONS } from "../../../openade-client/src"

export const COMPANION_RUNTIME_PERMISSIONS = OPENADE_PERMISSION_PROFILE_PAIRED_PERMISSIONS

export const COMPANION_RUNTIME_NOTIFICATION_PERMISSIONS = OPENADE_PERMISSION_PROFILE_PAIRED_NOTIFICATION_PERMISSIONS
