[[modules]]
name = "tmux"
type = "tmux-window"

	[modules.config]
	name = "frontend"

		[[modules.config.panes]]
		commands = ["(cd projects/electron && npm run start)"]

	    [[modules.config.panes]]
	    commands = ["(cd projects/web && npm run start)"]

		[[modules.config.panes]]
		commands = [""]

		[[modules.config.panes]]
		commands = [""] # blank as dev scratch pad



[[projects]]
name = "openade"
modules = ["tmux"]
