// Code generated by scripts/generate-openade-contracts.mjs from projects/openade-client/openade-contracts.json; DO NOT EDIT.

package product

import (
	"bytes"
	"encoding/json"
)

const (
	openADEMethodSnapshotRead                      = "openade/snapshot/read"
	openADEMethodProjectList                       = "openade/project/list"
	openADEMethodTaskList                          = "openade/task/list"
	openADEMethodTaskRead                          = "openade/task/read"
	openADEMethodProjectFileRead                   = "openade/project/file/read"
	openADEMethodProjectFilesTree                  = "openade/project/files/tree"
	openADEMethodProjectFilesFuzzySearch           = "openade/project/files/fuzzySearch"
	openADEMethodProjectFileWrite                  = "openade/project/file/write"
	openADEMethodProjectSearch                     = "openade/project/search"
	openADEMethodProjectSdkCapabilitiesRead        = "openade/project/sdkCapabilities/read"
	openADEMethodProjectGitInfoRead                = "openade/project/git/info/read"
	openADEMethodProjectGitBranchesRead            = "openade/project/git/branches/read"
	openADEMethodProjectGitSummaryRead             = "openade/project/git/summary/read"
	openADEMethodProjectProcessList                = "openade/project/process/list"
	openADEMethodCronDefinitionsRead               = "openade/cron/definitions/read"
	openADEMethodProjectProcessStart               = "openade/project/process/start"
	openADEMethodProjectProcessReconnect           = "openade/project/process/reconnect"
	openADEMethodProjectProcessStop                = "openade/project/process/stop"
	openADEMethodCronInstallStateList              = "openade/cron/installState/list"
	openADEMethodCronInstallStateRead              = "openade/cron/installState/read"
	openADEMethodCronInstallStateReplace           = "openade/cron/installState/replace"
	openADEMethodCronRun                           = "openade/cron/run"
	openADEMethodTaskChangesRead                   = "openade/task/changes/read"
	openADEMethodTaskGitSummaryRead                = "openade/task/git/summary/read"
	openADEMethodTaskGitScopesRead                 = "openade/task/git/scopes/read"
	openADEMethodTaskDiffRead                      = "openade/task/diff/read"
	openADEMethodTaskFilePairRead                  = "openade/task/filePair/read"
	openADEMethodTaskGitLog                        = "openade/task/git/log"
	openADEMethodTaskGitCommitFilesRead            = "openade/task/git/commit/files/read"
	openADEMethodTaskGitFileAtTreeishRead          = "openade/task/git/fileAtTreeish/read"
	openADEMethodTaskGitCommitFilePatchRead        = "openade/task/git/commit/filePatch/read"
	openADEMethodTaskGitCommit                     = "openade/task/git/commit"
	openADEMethodTaskTerminalStart                 = "openade/task/terminal/start"
	openADEMethodTaskTerminalReconnect             = "openade/task/terminal/reconnect"
	openADEMethodTaskTerminalWrite                 = "openade/task/terminal/write"
	openADEMethodTaskTerminalResize                = "openade/task/terminal/resize"
	openADEMethodTaskTerminalStop                  = "openade/task/terminal/stop"
	openADEMethodImportLegacyResources             = "openade/import/legacyResources"
	openADEMethodSettingsMcpServersRead            = "openade/settings/mcpServers/read"
	openADEMethodSettingsMcpServersReplace         = "openade/settings/mcpServers/replace"
	openADEMethodSettingsMcpServersUpsert          = "openade/settings/mcpServers/upsert"
	openADEMethodSettingsMcpServersDelete          = "openade/settings/mcpServers/delete"
	openADEMethodSettingsPersonalRead              = "openade/settings/personal/read"
	openADEMethodSettingsPersonalReplace           = "openade/settings/personal/replace"
	openADEMethodTaskImageRead                     = "openade/task/image/read"
	openADEMethodTaskImageStagedRead               = "openade/task/image/staged/read"
	openADEMethodTaskImageWrite                    = "openade/task/image/write"
	openADEMethodTaskImageImportLegacy             = "openade/task/image/importLegacy"
	openADEMethodTaskImagesImportLegacy            = "openade/task/images/importLegacy"
	openADEMethodTaskImagesGcStaged                = "openade/task/images/gcStaged"
	openADEMethodTaskSessionsImportLegacy          = "openade/task/sessions/importLegacy"
	openADEMethodTaskResourceInventoryRead         = "openade/task/resourceInventory/read"
	openADEMethodTaskTitleGenerate                 = "openade/task/title/generate"
	openADEMethodTaskSnapshotPatchRead             = "openade/task/snapshot/patch/read"
	openADEMethodTaskSnapshotIndexRead             = "openade/task/snapshot/index/read"
	openADEMethodTaskSnapshotPatchReadSlice        = "openade/task/snapshot/patch/readSlice"
	openADEMethodTaskSnapshotsImportLegacy         = "openade/task/snapshots/importLegacy"
	openADEMethodRepoPathInspect                   = "openade/repo/path/inspect"
	openADEMethodRepoCreate                        = "openade/repo/create"
	openADEMethodTaskCreate                        = "openade/task/create"
	openADEMethodRepoUpdate                        = "openade/repo/update"
	openADEMethodRepoDelete                        = "openade/repo/delete"
	openADEMethodTurnStart                         = "openade/turn/start"
	openADEMethodReviewStart                       = "openade/review/start"
	openADEMethodTurnInterrupt                     = "openade/turn/interrupt"
	openADEMethodQueuedTurnCancel                  = "openade/queued-turn/cancel"
	openADEMethodQueuedTurnEnqueue                 = "openade/queued-turn/enqueue"
	openADEMethodQueuedTurnImportLegacy            = "openade/queued-turn/importLegacy"
	openADEMethodQueuedTurnReorder                 = "openade/queued-turn/reorder"
	openADEMethodActionCreate                      = "openade/action/create"
	openADEMethodActionStreamAppend                = "openade/action/stream/append"
	openADEMethodActionComplete                    = "openade/action/complete"
	openADEMethodActionError                       = "openade/action/error"
	openADEMethodActionStopped                     = "openade/action/stopped"
	openADEMethodActionReconcileRuntime            = "openade/action/reconcileRuntime"
	openADEMethodActionExecutionUpdate             = "openade/action/execution/update"
	openADEMethodHyperplanSubExecutionAdd          = "openade/hyperplan/subExecution/add"
	openADEMethodHyperplanSubExecutionStreamAppend = "openade/hyperplan/subExecution/stream/append"
	openADEMethodHyperplanSubExecutionUpdate       = "openade/hyperplan/subExecution/update"
	openADEMethodHyperplanReconcileLabelsSet       = "openade/hyperplan/reconcileLabels/set"
	openADEMethodSnapshotCreate                    = "openade/snapshot/create"
	openADEMethodCommentCreate                     = "openade/comment/create"
	openADEMethodCommentEdit                       = "openade/comment/edit"
	openADEMethodCommentDelete                     = "openade/comment/delete"
	openADEMethodTaskMetadataUpdate                = "openade/task/metadata/update"
	openADEMethodTaskUsageBackfill                 = "openade/task/usage/backfill"
	openADEMethodTaskUsageRecalculate              = "openade/task/usage/recalculate"
	openADEMethodTaskDelete                        = "openade/task/delete"
	openADEMethodTaskEnvironmentSetup              = "openade/task/environment/setup"
	openADEMethodTaskEnvironmentPrepare            = "openade/task/environment/prepare"
)

const (
	openADERemoteMethodRemotePairingStart     = "remote/pairing/start"
	openADERemoteMethodRemoteDeviceList       = "remote/device/list"
	openADERemoteMethodRemoteDeviceRevoke     = "remote/device/revoke"
	openADERemoteMethodRemoteDeviceDropAll    = "remote/device/dropAll"
	openADERemoteMethodRemoteDeviceSelfRevoke = "remote/device/selfRevoke"
)

const (
	openADENotificationSnapshotChanged     = "openade/snapshotChanged"
	openADENotificationRepoUpdated         = "openade/repo/updated"
	openADENotificationRepoDeleted         = "openade/repo/deleted"
	openADENotificationTaskPreviewChanged  = "openade/task/previewChanged"
	openADENotificationTaskUpdated         = "openade/task/updated"
	openADENotificationTaskDeleted         = "openade/task/deleted"
	openADENotificationQueuedTurnUpdated   = "openade/queuedTurn/updated"
	openADENotificationWorkingTasks        = "openade/workingTasks"
	openADENotificationRemoteDeviceChanged = "remote/device/changed"
)

var openADEPermissionProfilePairedPermissions = []string{
	"initialize",
	"server/status/read",
	"subscription/update",
	openADERemoteMethodRemoteDeviceSelfRevoke,
	openADEMethodSnapshotRead,
	openADEMethodProjectList,
	openADEMethodProjectFilesTree,
	openADEMethodProjectFilesFuzzySearch,
	openADEMethodProjectFileRead,
	openADEMethodProjectSearch,
	openADEMethodProjectSdkCapabilitiesRead,
	openADEMethodProjectGitInfoRead,
	openADEMethodProjectGitBranchesRead,
	openADEMethodProjectGitSummaryRead,
	openADEMethodProjectProcessList,
	openADEMethodProjectProcessReconnect,
	openADEMethodCronDefinitionsRead,
	openADEMethodSettingsMcpServersRead,
	openADEMethodTaskList,
	openADEMethodTaskRead,
	openADEMethodTaskCreate,
	openADEMethodTaskChangesRead,
	openADEMethodTaskDiffRead,
	openADEMethodTaskFilePairRead,
	openADEMethodTaskGitSummaryRead,
	openADEMethodTaskGitLog,
	openADEMethodTaskGitScopesRead,
	openADEMethodTaskGitCommitFilesRead,
	openADEMethodTaskGitFileAtTreeishRead,
	openADEMethodTaskGitCommitFilePatchRead,
	openADEMethodTaskImageRead,
	openADEMethodTaskImageWrite,
	openADEMethodTaskResourceInventoryRead,
	openADEMethodTaskSnapshotPatchRead,
	openADEMethodTaskSnapshotIndexRead,
	openADEMethodTaskSnapshotPatchReadSlice,
	openADEMethodTurnStart,
	openADEMethodReviewStart,
	openADEMethodTurnInterrupt,
	openADEMethodQueuedTurnEnqueue,
	openADEMethodQueuedTurnReorder,
	openADEMethodQueuedTurnCancel,
	openADEMethodCommentCreate,
	openADEMethodCommentEdit,
	openADEMethodCommentDelete,
	openADEMethodTaskMetadataUpdate,
	openADEMethodTaskDelete,
}

var openADEPermissionProfilePairedNotificationPermissions = []string{
	"connection/*",
	openADENotificationRemoteDeviceChanged,
	"openade/*",
}

type openADEContractRequestKind uint8

const (
	openADEContractRequestObject openADEContractRequestKind = iota
	openADEContractRequestEmptyObject
	openADEContractRequestUndefined
)

type openADEContractFieldKind uint8

const (
	openADEContractFieldString openADEContractFieldKind = iota
	openADEContractFieldNumber
	openADEContractFieldBoolean
	openADEContractFieldArray
	openADEContractFieldObject
)

type openADEContractFieldValidator struct {
	Name     string
	Kind     openADEContractFieldKind
	Required bool
	Values   []string
}

var openADEContractRequestKinds = map[string]openADEContractRequestKind{
	openADEMethodSnapshotRead:                      openADEContractRequestUndefined,
	openADEMethodProjectList:                       openADEContractRequestUndefined,
	openADEMethodTaskList:                          openADEContractRequestObject,
	openADEMethodTaskRead:                          openADEContractRequestObject,
	openADEMethodProjectFileRead:                   openADEContractRequestObject,
	openADEMethodProjectFilesTree:                  openADEContractRequestObject,
	openADEMethodProjectFilesFuzzySearch:           openADEContractRequestObject,
	openADEMethodProjectFileWrite:                  openADEContractRequestObject,
	openADEMethodProjectSearch:                     openADEContractRequestObject,
	openADEMethodProjectSdkCapabilitiesRead:        openADEContractRequestObject,
	openADEMethodProjectGitInfoRead:                openADEContractRequestObject,
	openADEMethodProjectGitBranchesRead:            openADEContractRequestObject,
	openADEMethodProjectGitSummaryRead:             openADEContractRequestObject,
	openADEMethodProjectProcessList:                openADEContractRequestObject,
	openADEMethodCronDefinitionsRead:               openADEContractRequestObject,
	openADEMethodProjectProcessStart:               openADEContractRequestObject,
	openADEMethodProjectProcessReconnect:           openADEContractRequestObject,
	openADEMethodProjectProcessStop:                openADEContractRequestObject,
	openADEMethodCronInstallStateList:              openADEContractRequestUndefined,
	openADEMethodCronInstallStateRead:              openADEContractRequestObject,
	openADEMethodCronInstallStateReplace:           openADEContractRequestObject,
	openADEMethodCronRun:                           openADEContractRequestObject,
	openADEMethodTaskChangesRead:                   openADEContractRequestObject,
	openADEMethodTaskGitSummaryRead:                openADEContractRequestObject,
	openADEMethodTaskGitScopesRead:                 openADEContractRequestObject,
	openADEMethodTaskDiffRead:                      openADEContractRequestObject,
	openADEMethodTaskFilePairRead:                  openADEContractRequestObject,
	openADEMethodTaskGitLog:                        openADEContractRequestObject,
	openADEMethodTaskGitCommitFilesRead:            openADEContractRequestObject,
	openADEMethodTaskGitFileAtTreeishRead:          openADEContractRequestObject,
	openADEMethodTaskGitCommitFilePatchRead:        openADEContractRequestObject,
	openADEMethodTaskGitCommit:                     openADEContractRequestObject,
	openADEMethodTaskTerminalStart:                 openADEContractRequestObject,
	openADEMethodTaskTerminalReconnect:             openADEContractRequestObject,
	openADEMethodTaskTerminalWrite:                 openADEContractRequestObject,
	openADEMethodTaskTerminalResize:                openADEContractRequestObject,
	openADEMethodTaskTerminalStop:                  openADEContractRequestObject,
	openADEMethodImportLegacyResources:             openADEContractRequestObject,
	openADEMethodSettingsMcpServersRead:            openADEContractRequestEmptyObject,
	openADEMethodSettingsMcpServersReplace:         openADEContractRequestObject,
	openADEMethodSettingsMcpServersUpsert:          openADEContractRequestObject,
	openADEMethodSettingsMcpServersDelete:          openADEContractRequestObject,
	openADEMethodSettingsPersonalRead:              openADEContractRequestEmptyObject,
	openADEMethodSettingsPersonalReplace:           openADEContractRequestObject,
	openADEMethodTaskImageRead:                     openADEContractRequestObject,
	openADEMethodTaskImageStagedRead:               openADEContractRequestObject,
	openADEMethodTaskImageWrite:                    openADEContractRequestObject,
	openADEMethodTaskImageImportLegacy:             openADEContractRequestObject,
	openADEMethodTaskImagesImportLegacy:            openADEContractRequestObject,
	openADEMethodTaskImagesGcStaged:                openADEContractRequestObject,
	openADEMethodTaskSessionsImportLegacy:          openADEContractRequestObject,
	openADEMethodTaskResourceInventoryRead:         openADEContractRequestObject,
	openADEMethodTaskTitleGenerate:                 openADEContractRequestObject,
	openADEMethodTaskSnapshotPatchRead:             openADEContractRequestObject,
	openADEMethodTaskSnapshotIndexRead:             openADEContractRequestObject,
	openADEMethodTaskSnapshotPatchReadSlice:        openADEContractRequestObject,
	openADEMethodTaskSnapshotsImportLegacy:         openADEContractRequestObject,
	openADEMethodRepoPathInspect:                   openADEContractRequestObject,
	openADEMethodRepoCreate:                        openADEContractRequestObject,
	openADEMethodTaskCreate:                        openADEContractRequestObject,
	openADEMethodRepoUpdate:                        openADEContractRequestObject,
	openADEMethodRepoDelete:                        openADEContractRequestObject,
	openADEMethodTurnStart:                         openADEContractRequestObject,
	openADEMethodReviewStart:                       openADEContractRequestObject,
	openADEMethodTurnInterrupt:                     openADEContractRequestObject,
	openADEMethodQueuedTurnCancel:                  openADEContractRequestObject,
	openADEMethodQueuedTurnEnqueue:                 openADEContractRequestObject,
	openADEMethodQueuedTurnImportLegacy:            openADEContractRequestObject,
	openADEMethodQueuedTurnReorder:                 openADEContractRequestObject,
	openADEMethodActionCreate:                      openADEContractRequestObject,
	openADEMethodActionStreamAppend:                openADEContractRequestObject,
	openADEMethodActionComplete:                    openADEContractRequestObject,
	openADEMethodActionError:                       openADEContractRequestObject,
	openADEMethodActionStopped:                     openADEContractRequestObject,
	openADEMethodActionReconcileRuntime:            openADEContractRequestObject,
	openADEMethodActionExecutionUpdate:             openADEContractRequestObject,
	openADEMethodHyperplanSubExecutionAdd:          openADEContractRequestObject,
	openADEMethodHyperplanSubExecutionStreamAppend: openADEContractRequestObject,
	openADEMethodHyperplanSubExecutionUpdate:       openADEContractRequestObject,
	openADEMethodHyperplanReconcileLabelsSet:       openADEContractRequestObject,
	openADEMethodSnapshotCreate:                    openADEContractRequestObject,
	openADEMethodCommentCreate:                     openADEContractRequestObject,
	openADEMethodCommentEdit:                       openADEContractRequestObject,
	openADEMethodCommentDelete:                     openADEContractRequestObject,
	openADEMethodTaskMetadataUpdate:                openADEContractRequestObject,
	openADEMethodTaskUsageBackfill:                 openADEContractRequestObject,
	openADEMethodTaskUsageRecalculate:              openADEContractRequestObject,
	openADEMethodTaskDelete:                        openADEContractRequestObject,
	openADEMethodTaskEnvironmentSetup:              openADEContractRequestObject,
	openADEMethodTaskEnvironmentPrepare:            openADEContractRequestObject,
	openADERemoteMethodRemotePairingStart:          openADEContractRequestObject,
	openADERemoteMethodRemoteDeviceList:            openADEContractRequestUndefined,
	openADERemoteMethodRemoteDeviceRevoke:          openADEContractRequestObject,
	openADERemoteMethodRemoteDeviceDropAll:         openADEContractRequestUndefined,
	openADERemoteMethodRemoteDeviceSelfRevoke:      openADEContractRequestUndefined,
}

var openADEContractFields = map[string][]openADEContractFieldValidator{
	openADEMethodTaskList: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodTaskRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "hydrateSessionEvents", Kind: openADEContractFieldBoolean, Required: false},
		{Name: "eventLimit", Kind: openADEContractFieldNumber, Required: false},
	},
	openADEMethodProjectFileRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: false},
		{Name: "path", Kind: openADEContractFieldString, Required: true},
		{Name: "encoding", Kind: openADEContractFieldString, Required: false, Values: []string{"utf8", "base64"}},
		{Name: "maxBytes", Kind: openADEContractFieldNumber, Required: false},
	},
	openADEMethodProjectFilesTree: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: false},
		{Name: "path", Kind: openADEContractFieldString, Required: false},
		{Name: "maxDepth", Kind: openADEContractFieldNumber, Required: false},
		{Name: "maxEntries", Kind: openADEContractFieldNumber, Required: false},
		{Name: "includeHidden", Kind: openADEContractFieldBoolean, Required: false},
		{Name: "includeGenerated", Kind: openADEContractFieldBoolean, Required: false},
	},
	openADEMethodProjectFilesFuzzySearch: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: false},
		{Name: "query", Kind: openADEContractFieldString, Required: true},
		{Name: "matchDirs", Kind: openADEContractFieldBoolean, Required: false},
		{Name: "limit", Kind: openADEContractFieldNumber, Required: false},
		{Name: "includeHidden", Kind: openADEContractFieldBoolean, Required: false},
		{Name: "includeGenerated", Kind: openADEContractFieldBoolean, Required: false},
	},
	openADEMethodProjectFileWrite: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: false},
		{Name: "path", Kind: openADEContractFieldString, Required: true},
		{Name: "encoding", Kind: openADEContractFieldString, Required: false, Values: []string{"utf8", "base64"}},
		{Name: "content", Kind: openADEContractFieldString, Required: true},
		{Name: "createDirs", Kind: openADEContractFieldBoolean, Required: false},
	},
	openADEMethodProjectSearch: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: false},
		{Name: "query", Kind: openADEContractFieldString, Required: true},
		{Name: "limit", Kind: openADEContractFieldNumber, Required: false},
		{Name: "caseSensitive", Kind: openADEContractFieldBoolean, Required: false},
	},
	openADEMethodProjectSdkCapabilitiesRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: false},
		{Name: "harnessId", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodProjectGitInfoRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodProjectGitBranchesRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "includeRemote", Kind: openADEContractFieldBoolean, Required: false},
	},
	openADEMethodProjectGitSummaryRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodProjectProcessList: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodCronDefinitionsRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodProjectProcessStart: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: false},
		{Name: "definitionId", Kind: openADEContractFieldString, Required: true},
		{Name: "timeoutMs", Kind: openADEContractFieldNumber, Required: false},
	},
	openADEMethodProjectProcessReconnect: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: false},
		{Name: "processId", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodProjectProcessStop: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: false},
		{Name: "processId", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodCronInstallStateRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodCronInstallStateReplace: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "installations", Kind: openADEContractFieldObject, Required: true},
	},
	openADEMethodCronRun: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "cronId", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodTaskChangesRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "fromTreeish", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodTaskGitSummaryRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodTaskGitScopesRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "includeRemote", Kind: openADEContractFieldBoolean, Required: false},
	},
	openADEMethodTaskDiffRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "filePath", Kind: openADEContractFieldString, Required: true},
		{Name: "oldPath", Kind: openADEContractFieldString, Required: false},
		{Name: "fromTreeish", Kind: openADEContractFieldString, Required: false},
		{Name: "contextLines", Kind: openADEContractFieldNumber, Required: false},
		{Name: "allowTruncation", Kind: openADEContractFieldBoolean, Required: false},
	},
	openADEMethodTaskFilePairRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "filePath", Kind: openADEContractFieldString, Required: true},
		{Name: "oldPath", Kind: openADEContractFieldString, Required: false},
		{Name: "fromTreeish", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodTaskGitLog: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "scopeId", Kind: openADEContractFieldString, Required: false},
		{Name: "ref", Kind: openADEContractFieldString, Required: false},
		{Name: "limit", Kind: openADEContractFieldNumber, Required: false},
		{Name: "skip", Kind: openADEContractFieldNumber, Required: false},
	},
	openADEMethodTaskGitCommitFilesRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "commit", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodTaskGitFileAtTreeishRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "treeish", Kind: openADEContractFieldString, Required: true},
		{Name: "filePath", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodTaskGitCommitFilePatchRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "commit", Kind: openADEContractFieldString, Required: true},
		{Name: "filePath", Kind: openADEContractFieldString, Required: true},
		{Name: "oldPath", Kind: openADEContractFieldString, Required: false},
		{Name: "contextLines", Kind: openADEContractFieldNumber, Required: false},
		{Name: "allowTruncation", Kind: openADEContractFieldBoolean, Required: false},
	},
	openADEMethodTaskGitCommit: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "message", Kind: openADEContractFieldString, Required: true},
		{Name: "clientRequestId", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodTaskTerminalStart: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "cols", Kind: openADEContractFieldNumber, Required: false},
		{Name: "rows", Kind: openADEContractFieldNumber, Required: false},
	},
	openADEMethodTaskTerminalReconnect: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "terminalId", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodTaskTerminalWrite: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "terminalId", Kind: openADEContractFieldString, Required: true},
		{Name: "data", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodTaskTerminalResize: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "terminalId", Kind: openADEContractFieldString, Required: true},
		{Name: "cols", Kind: openADEContractFieldNumber, Required: true},
		{Name: "rows", Kind: openADEContractFieldNumber, Required: true},
	},
	openADEMethodTaskTerminalStop: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "terminalId", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodImportLegacyResources: {
		{Name: "dataDir", Kind: openADEContractFieldString, Required: false},
		{Name: "imageDir", Kind: openADEContractFieldString, Required: false},
		{Name: "snapshotDir", Kind: openADEContractFieldString, Required: false},
		{Name: "importSessions", Kind: openADEContractFieldBoolean, Required: false},
		{Name: "claudeConfigDir", Kind: openADEContractFieldString, Required: false},
		{Name: "codexHome", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodSettingsMcpServersReplace: {
		{Name: "servers", Kind: openADEContractFieldArray, Required: true},
	},
	openADEMethodSettingsMcpServersUpsert: {
		{Name: "server", Kind: openADEContractFieldObject, Required: true},
	},
	openADEMethodSettingsMcpServersDelete: {
		{Name: "serverId", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodSettingsPersonalReplace: {
		{Name: "settings", Kind: openADEContractFieldObject, Required: true},
	},
	openADEMethodTaskImageRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "imageId", Kind: openADEContractFieldString, Required: true},
		{Name: "ext", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodTaskImageStagedRead: {
		{Name: "imageId", Kind: openADEContractFieldString, Required: true},
		{Name: "ext", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodTaskImageWrite: {
		{Name: "imageId", Kind: openADEContractFieldString, Required: true},
		{Name: "ext", Kind: openADEContractFieldString, Required: true, Values: []string{"gif", "jpeg", "jpg", "png", "webp"}},
		{Name: "mediaType", Kind: openADEContractFieldString, Required: true, Values: []string{"image/gif", "image/jpeg", "image/png", "image/webp"}},
		{Name: "data", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodTaskImageImportLegacy: {
		{Name: "imageId", Kind: openADEContractFieldString, Required: true},
		{Name: "ext", Kind: openADEContractFieldString, Required: true, Values: []string{"gif", "jpeg", "jpg", "png", "webp"}},
		{Name: "mediaType", Kind: openADEContractFieldString, Required: true, Values: []string{"image/gif", "image/jpeg", "image/png", "image/webp"}},
		{Name: "sourcePath", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodTaskImagesImportLegacy: {
		{Name: "sourceDir", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodTaskImagesGcStaged: {
		{Name: "olderThanMs", Kind: openADEContractFieldNumber, Required: false},
		{Name: "dryRun", Kind: openADEContractFieldBoolean, Required: false},
	},
	openADEMethodTaskSessionsImportLegacy: {
		{Name: "claudeConfigDir", Kind: openADEContractFieldString, Required: false},
		{Name: "codexHome", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodTaskResourceInventoryRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodTaskTitleGenerate: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "harnessId", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodTaskSnapshotPatchRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "eventId", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodTaskSnapshotIndexRead: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "eventId", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodTaskSnapshotPatchReadSlice: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "eventId", Kind: openADEContractFieldString, Required: true},
		{Name: "start", Kind: openADEContractFieldNumber, Required: true},
		{Name: "end", Kind: openADEContractFieldNumber, Required: true},
	},
	openADEMethodTaskSnapshotsImportLegacy: {
		{Name: "sourceDir", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodRepoPathInspect: {
		{Name: "path", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodRepoCreate: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: false},
		{Name: "name", Kind: openADEContractFieldString, Required: true},
		{Name: "path", Kind: openADEContractFieldString, Required: true},
		{Name: "createdBy", Kind: openADEContractFieldObject, Required: true},
		{Name: "createdAt", Kind: openADEContractFieldString, Required: false},
		{Name: "createDirectory", Kind: openADEContractFieldBoolean, Required: false},
		{Name: "initializeGit", Kind: openADEContractFieldBoolean, Required: false},
	},
	openADEMethodTaskCreate: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "input", Kind: openADEContractFieldString, Required: true},
		{Name: "createdBy", Kind: openADEContractFieldObject, Required: true},
		{Name: "deviceId", Kind: openADEContractFieldString, Required: true},
		{Name: "title", Kind: openADEContractFieldString, Required: false},
		{Name: "taskId", Kind: openADEContractFieldString, Required: false},
		{Name: "slug", Kind: openADEContractFieldString, Required: false},
		{Name: "createdAt", Kind: openADEContractFieldString, Required: false},
		{Name: "isolationStrategy", Kind: openADEContractFieldObject, Required: false},
		{Name: "enabledMcpServerIds", Kind: openADEContractFieldArray, Required: false},
		{Name: "deviceEnvironment", Kind: openADEContractFieldObject, Required: false},
		{Name: "setupEvent", Kind: openADEContractFieldObject, Required: false},
	},
	openADEMethodRepoUpdate: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "name", Kind: openADEContractFieldString, Required: false},
		{Name: "path", Kind: openADEContractFieldString, Required: false},
		{Name: "archived", Kind: openADEContractFieldBoolean, Required: false},
		{Name: "updatedAt", Kind: openADEContractFieldString, Required: false},
		{Name: "initializeGit", Kind: openADEContractFieldBoolean, Required: false},
	},
	openADEMethodRepoDelete: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodTurnStart: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "type", Kind: openADEContractFieldString, Required: true, Values: []string{"plan", "do", "ask", "revise", "run_plan", "hyperplan"}},
		{Name: "input", Kind: openADEContractFieldString, Required: true},
		{Name: "appendSystemPrompt", Kind: openADEContractFieldString, Required: false},
		{Name: "inTaskId", Kind: openADEContractFieldString, Required: false},
		{Name: "isolationStrategy", Kind: openADEContractFieldObject, Required: false},
		{Name: "enabledMcpServerIds", Kind: openADEContractFieldArray, Required: false},
		{Name: "harnessId", Kind: openADEContractFieldString, Required: false},
		{Name: "modelId", Kind: openADEContractFieldString, Required: false},
		{Name: "label", Kind: openADEContractFieldString, Required: false},
		{Name: "includeComments", Kind: openADEContractFieldBoolean, Required: false},
		{Name: "images", Kind: openADEContractFieldArray, Required: false},
		{Name: "thinking", Kind: openADEContractFieldString, Required: false, Values: []string{"low", "med", "high", "max"}},
		{Name: "fastMode", Kind: openADEContractFieldBoolean, Required: false},
		{Name: "title", Kind: openADEContractFieldString, Required: false},
		{Name: "hyperplanStrategy", Kind: openADEContractFieldObject, Required: false},
	},
	openADEMethodReviewStart: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "reviewType", Kind: openADEContractFieldString, Required: true, Values: []string{"plan", "work"}},
		{Name: "harnessId", Kind: openADEContractFieldString, Required: true},
		{Name: "modelId", Kind: openADEContractFieldString, Required: true},
		{Name: "thinking", Kind: openADEContractFieldString, Required: false, Values: []string{"low", "med", "high", "max"}},
		{Name: "fastMode", Kind: openADEContractFieldBoolean, Required: false},
		{Name: "customInstructions", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodTurnInterrupt: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "clientRequestId", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodQueuedTurnCancel: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "queuedTurnId", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodQueuedTurnEnqueue: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "type", Kind: openADEContractFieldString, Required: true, Values: []string{"do", "ask", "hyperplan"}},
		{Name: "input", Kind: openADEContractFieldString, Required: true},
		{Name: "queuedTurnId", Kind: openADEContractFieldString, Required: false},
		{Name: "createdAt", Kind: openADEContractFieldString, Required: false},
		{Name: "eventId", Kind: openADEContractFieldString, Required: false},
		{Name: "appendSystemPrompt", Kind: openADEContractFieldString, Required: false},
		{Name: "enabledMcpServerIds", Kind: openADEContractFieldArray, Required: false},
		{Name: "harnessId", Kind: openADEContractFieldString, Required: false},
		{Name: "modelId", Kind: openADEContractFieldString, Required: false},
		{Name: "label", Kind: openADEContractFieldString, Required: false},
		{Name: "includeComments", Kind: openADEContractFieldBoolean, Required: false},
		{Name: "images", Kind: openADEContractFieldArray, Required: false},
		{Name: "hyperplanStrategy", Kind: openADEContractFieldObject, Required: false},
		{Name: "thinking", Kind: openADEContractFieldString, Required: false, Values: []string{"low", "med", "high", "max"}},
		{Name: "fastMode", Kind: openADEContractFieldBoolean, Required: false},
	},
	openADEMethodQueuedTurnImportLegacy: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "turn", Kind: openADEContractFieldObject, Required: true},
		{Name: "position", Kind: openADEContractFieldNumber, Required: false},
	},
	openADEMethodQueuedTurnReorder: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "queuedTurnIds", Kind: openADEContractFieldArray, Required: true},
		{Name: "updatedAt", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodActionCreate: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "userInput", Kind: openADEContractFieldString, Required: true},
		{Name: "executionId", Kind: openADEContractFieldString, Required: true},
		{Name: "harnessId", Kind: openADEContractFieldString, Required: true},
		{Name: "source", Kind: openADEContractFieldObject, Required: true},
		{Name: "eventId", Kind: openADEContractFieldString, Required: false},
		{Name: "createdAt", Kind: openADEContractFieldString, Required: false},
		{Name: "images", Kind: openADEContractFieldArray, Required: false},
		{Name: "includesCommentIds", Kind: openADEContractFieldArray, Required: false},
		{Name: "modelId", Kind: openADEContractFieldString, Required: false},
		{Name: "fastMode", Kind: openADEContractFieldBoolean, Required: false},
		{Name: "gitRefsBefore", Kind: openADEContractFieldObject, Required: false},
	},
	openADEMethodActionStreamAppend: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "eventId", Kind: openADEContractFieldString, Required: true},
		{Name: "streamEvent", Kind: openADEContractFieldObject, Required: true},
	},
	openADEMethodActionComplete: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "eventId", Kind: openADEContractFieldString, Required: true},
		{Name: "success", Kind: openADEContractFieldBoolean, Required: true},
		{Name: "completedAt", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodActionError: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "eventId", Kind: openADEContractFieldString, Required: true},
		{Name: "completedAt", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodActionStopped: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "eventId", Kind: openADEContractFieldString, Required: true},
		{Name: "completedAt", Kind: openADEContractFieldString, Required: false},
		{Name: "sessionId", Kind: openADEContractFieldString, Required: false},
		{Name: "parentSessionId", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodActionReconcileRuntime: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "eventId", Kind: openADEContractFieldString, Required: false},
		{Name: "executionId", Kind: openADEContractFieldString, Required: false},
		{Name: "status", Kind: openADEContractFieldString, Required: true, Values: []string{"completed", "failed", "stopped"}},
		{Name: "success", Kind: openADEContractFieldBoolean, Required: false},
		{Name: "completedAt", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodActionExecutionUpdate: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "eventId", Kind: openADEContractFieldString, Required: true},
		{Name: "sessionId", Kind: openADEContractFieldString, Required: false},
		{Name: "parentSessionId", Kind: openADEContractFieldString, Required: false},
		{Name: "gitRefsAfter", Kind: openADEContractFieldObject, Required: false},
	},
	openADEMethodHyperplanSubExecutionAdd: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "eventId", Kind: openADEContractFieldString, Required: true},
		{Name: "subExecution", Kind: openADEContractFieldObject, Required: true},
	},
	openADEMethodHyperplanSubExecutionStreamAppend: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "eventId", Kind: openADEContractFieldString, Required: true},
		{Name: "stepId", Kind: openADEContractFieldString, Required: true},
		{Name: "streamEvent", Kind: openADEContractFieldObject, Required: true},
	},
	openADEMethodHyperplanSubExecutionUpdate: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "eventId", Kind: openADEContractFieldString, Required: true},
		{Name: "stepId", Kind: openADEContractFieldString, Required: true},
		{Name: "executionId", Kind: openADEContractFieldString, Required: false},
		{Name: "sessionId", Kind: openADEContractFieldString, Required: false},
		{Name: "parentSessionId", Kind: openADEContractFieldString, Required: false},
		{Name: "status", Kind: openADEContractFieldString, Required: false, Values: []string{"in_progress", "completed", "error", "stopped"}},
		{Name: "resultText", Kind: openADEContractFieldString, Required: false},
		{Name: "error", Kind: openADEContractFieldString, Required: false},
		{Name: "reconcileLabel", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodHyperplanReconcileLabelsSet: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "eventId", Kind: openADEContractFieldString, Required: true},
		{Name: "mapping", Kind: openADEContractFieldArray, Required: true},
	},
	openADEMethodSnapshotCreate: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "actionEventId", Kind: openADEContractFieldString, Required: true},
		{Name: "referenceBranch", Kind: openADEContractFieldString, Required: true},
		{Name: "mergeBaseCommit", Kind: openADEContractFieldString, Required: true},
		{Name: "fullPatch", Kind: openADEContractFieldString, Required: true},
		{Name: "patchFileId", Kind: openADEContractFieldString, Required: false},
		{Name: "stats", Kind: openADEContractFieldObject, Required: true},
		{Name: "files", Kind: openADEContractFieldArray, Required: false},
		{Name: "eventId", Kind: openADEContractFieldString, Required: false},
		{Name: "createdAt", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodCommentCreate: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "content", Kind: openADEContractFieldString, Required: true},
		{Name: "source", Kind: openADEContractFieldObject, Required: true},
		{Name: "selectedText", Kind: openADEContractFieldObject, Required: true},
		{Name: "author", Kind: openADEContractFieldObject, Required: true},
		{Name: "commentId", Kind: openADEContractFieldString, Required: false},
		{Name: "createdAt", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodCommentEdit: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "commentId", Kind: openADEContractFieldString, Required: true},
		{Name: "content", Kind: openADEContractFieldString, Required: true},
		{Name: "updatedAt", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodCommentDelete: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "commentId", Kind: openADEContractFieldString, Required: true},
		{Name: "updatedAt", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodTaskMetadataUpdate: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: false},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "title", Kind: openADEContractFieldString, Required: false},
		{Name: "closed", Kind: openADEContractFieldBoolean, Required: false},
		{Name: "lastViewedAt", Kind: openADEContractFieldString, Required: false},
		{Name: "lastEventAt", Kind: openADEContractFieldString, Required: false},
		{Name: "cancelledPlanEventId", Kind: openADEContractFieldString, Required: false},
		{Name: "usage", Kind: openADEContractFieldObject, Required: false},
		{Name: "enabledMcpServerIds", Kind: openADEContractFieldArray, Required: false},
		{Name: "sessionIds", Kind: openADEContractFieldObject, Required: false},
		{Name: "queuedTurns", Kind: openADEContractFieldArray, Required: false},
		{Name: "updatedAt", Kind: openADEContractFieldString, Required: false},
	},
	openADEMethodTaskUsageBackfill: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: false},
		{Name: "taskIds", Kind: openADEContractFieldArray, Required: false},
		{Name: "force", Kind: openADEContractFieldBoolean, Required: false},
	},
	openADEMethodTaskUsageRecalculate: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
	},
	openADEMethodTaskDelete: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "options", Kind: openADEContractFieldObject, Required: false},
	},
	openADEMethodTaskEnvironmentSetup: {
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
		{Name: "deviceEnvironment", Kind: openADEContractFieldObject, Required: true},
		{Name: "setupEvent", Kind: openADEContractFieldObject, Required: false},
	},
	openADEMethodTaskEnvironmentPrepare: {
		{Name: "repoId", Kind: openADEContractFieldString, Required: true},
		{Name: "taskId", Kind: openADEContractFieldString, Required: true},
	},
	openADERemoteMethodRemotePairingStart: {
		{Name: "baseUrl", Kind: openADEContractFieldString, Required: true},
		{Name: "hostId", Kind: openADEContractFieldString, Required: false},
	},
	openADERemoteMethodRemoteDeviceRevoke: {
		{Name: "deviceId", Kind: openADEContractFieldString, Required: true},
	},
}

func normalizeOpenADEContractRequest(method string, raw json.RawMessage) (json.RawMessage, string) {
	kind, ok := openADEContractRequestKinds[method]
	if !ok {
		return raw, ""
	}
	trimmed := bytes.TrimSpace(raw)
	switch kind {
	case openADEContractRequestUndefined:
		if len(trimmed) == 0 || bytes.Equal(trimmed, []byte("null")) {
			return raw, ""
		}
		if object, ok := openADEContractObjectFields(trimmed); ok && len(object) == 0 {
			return raw, ""
		}
		return raw, "params must be omitted for this method"
	case openADEContractRequestEmptyObject:
		if len(trimmed) == 0 || bytes.Equal(trimmed, []byte("null")) {
			return json.RawMessage(`{}`), ""
		}
		if object, ok := openADEContractObjectFields(trimmed); ok {
			if len(object) == 0 {
				return raw, ""
			}
			return raw, "params must be an empty object for this method"
		}
		return raw, "params must be an empty object for this method"
	default:
		if object, ok := openADEContractObjectFields(trimmed); ok {
			if message := validateOpenADEContractFields(method, object); message != "" {
				return raw, message
			}
			return raw, ""
		}
		return raw, "params must be an object"
	}
}

func openADEContractObjectFields(raw []byte) (map[string]json.RawMessage, bool) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(raw, &object); err != nil || object == nil {
		return nil, false
	}
	return object, true
}

func validateOpenADEContractFields(method string, object map[string]json.RawMessage) string {
	for _, field := range openADEContractFields[method] {
		raw, ok := object[field.Name]
		if !ok || bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
			if !field.Required {
				continue
			}
			return "params." + field.Name + " is required"
		}
		if !openADEContractFieldMatches(field.Kind, raw) {
			return "params." + field.Name + " has the wrong type"
		}
		if len(field.Values) > 0 && !openADEContractStringValueAllowed(raw, field.Values) {
			return "params." + field.Name + " has an unsupported value"
		}
	}
	return ""
}

func openADEContractStringValueAllowed(raw json.RawMessage, allowed []string) bool {
	var value string
	if err := json.Unmarshal(raw, &value); err != nil {
		return false
	}
	for _, allowedValue := range allowed {
		if value == allowedValue {
			return true
		}
	}
	return false
}

func openADEContractFieldMatches(kind openADEContractFieldKind, raw json.RawMessage) bool {
	switch kind {
	case openADEContractFieldString:
		var value string
		return json.Unmarshal(raw, &value) == nil
	case openADEContractFieldNumber:
		var value float64
		return json.Unmarshal(raw, &value) == nil
	case openADEContractFieldBoolean:
		var value bool
		return json.Unmarshal(raw, &value) == nil
	case openADEContractFieldArray:
		var value []json.RawMessage
		return json.Unmarshal(raw, &value) == nil
	case openADEContractFieldObject:
		var value map[string]json.RawMessage
		return json.Unmarshal(raw, &value) == nil && value != nil
	}
	return true
}
